# A workflow to validate JSON files against JSON Schemata

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for JSON files
  pull_request:
    branches: [ '**' ]
    paths: [ '**.json' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_json_schema:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Validate zones.json
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          schema: ./config/zones.schema.json
          json: ./config/zones.json
      - name: Validate exchanges.json
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          schema: ./config/exchanges.schema.json
          json: ./config/exchanges.json
